In [81]:
import pandas as pd
import numpy as np

In [3]:
train = pd.read_csv("C:/Users/hp/Documents/Azubi_2/project_2/Customer_churn_prediction/data/training.csv")
test = pd.read_csv("C:/Users/hp/Documents/Azubi_2/project_2/Customer_churn_prediction/data/testing.csv")

In [4]:
train.shape , test.shape

((5043, 22), (2000, 21))

## Handling Missing Values

In [5]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy= "median" )

In [7]:
train_num = train[["tenure", "MonthlyCharges", "TotalCharges"]] # selecting only numerical columns

In [8]:
train_num

tenure  MonthlyCharges  TotalCharges
0          1       29.850000     29.850000
1         34       56.950001   1889.500000
2          2       53.849998    108.150002
3         45       42.299999   1840.750000
4          2       70.699997    151.649994
...      ...             ...           ...
5038      24       84.800000   1990.500000
5039      72      103.200000   7362.900000
5040      11       29.600000    346.450000
5041       4       74.400000    306.600000
5042      66      105.650000   6844.500000

[5043 rows x 3 columns]

In [9]:
imputer.fit(train_num)

SimpleImputer(strategy='median')

In [10]:
imputer.statistics_

array([  29.        ,   70.55000305, 1401.4       ])

In [11]:
train_num.median().values

array([  29.        ,   70.55000305, 1401.4       ])

In [12]:
X = imputer.transform(train_num) # replacing median value if there

In [13]:
X

array([[1.00000000e+00, 2.98500004e+01, 2.98500004e+01],
       [3.40000000e+01, 5.69500008e+01, 1.88950000e+03],
       [2.00000000e+00, 5.38499985e+01, 1.08150002e+02],
       ...,
       [1.10000000e+01, 2.96000000e+01, 3.46450000e+02],
       [4.00000000e+00, 7.44000000e+01, 3.06600000e+02],
       [6.60000000e+01, 1.05650000e+02, 6.84450000e+03]])

In [14]:
train_tr = pd.DataFrame(X, columns=train_num.columns) # converting to data frame

In [15]:
train_tr

tenure  MonthlyCharges  TotalCharges
0        1.0       29.850000     29.850000
1       34.0       56.950001   1889.500000
2        2.0       53.849998    108.150002
3       45.0       42.299999   1840.750000
4        2.0       70.699997    151.649994
...      ...             ...           ...
5038    24.0       84.800000   1990.500000
5039    72.0      103.200000   7362.900000
5040    11.0       29.600000    346.450000
5041     4.0       74.400000    306.600000
5042    66.0      105.650000   6844.500000

[5043 rows x 3 columns]

## Handling Categorical Features

In [16]:
train_cat = train["gender"]

In [20]:
train_cat = train_cat.array.reshape(-1 , 1)

In [21]:
from sklearn.preprocessing import OrdinalEncoder

cat_encoder = OrdinalEncoder()

train_cat_1hot = cat_encoder.fit_transform(train_cat) 

train_cat_1hot

array([[0.],
       [1.],
       [1.],
       ...,
       [0.],
       [1.],
       [1.]])

In [25]:
cat_encoder.categories_

[array(['Female', 'Male'], dtype=object)]

In [29]:
train_cat = train.drop(["tenure", "MonthlyCharges", "TotalCharges"], axis = 1) # selecting only categorical columns

In [30]:
train_cat

Column1  customerID  gender SeniorCitizen Partner Dependents  \
0           0  7590-VHVEG  Female            No     Yes         No   
1           1  5575-GNVDE    Male            No      No         No   
2           2  3668-QPYBK    Male            No      No         No   
3           3  7795-CFOCW    Male            No      No         No   
4           4  9237-HQITU  Female            No      No         No   
...       ...         ...     ...           ...     ...        ...   
5038     2038  6840-RESVB    Male            No     Yes        Yes   
5039     2039  2234-XADUH  Female            No     Yes        Yes   
5040     2040  4801-JZAZL  Female            No     Yes        Yes   
5041     2041  8361-LTMKD    Male           Yes     Yes         No   
5042     2042  3186-AJIEK    Male            No      No         No   

     PhoneService     MultipleLines InternetService OnlineSecurity  \
0              No                No             DSL             No   
1             Yes                No             DSL            Yes   
2             Yes                No             DSL            Yes   
3              No                No             DSL            Yes   
4             Yes                No     Fiber optic             No   
...           ...               ...             ...            ...   
5038          Yes               Yes             DSL            Yes   
5039          Yes               Yes     Fiber optic             No   
5040           No  No phone service             DSL            Yes   
5041          Yes               Yes     Fiber optic             No   
5042          Yes                No     Fiber optic            Yes   

     OnlineBackup DeviceProtection TechSupport StreamingTV StreamingMovies  \
0             Yes               No          No          No              No   
1              No              Yes          No          No              No   
2             Yes               No          No          No              No   
3              No              Yes         Yes          No              No   
4              No               No          No          No              No   
...           ...              ...         ...         ...             ...   
5038           No              Yes         Yes         Yes             Yes   
5039          Yes              Yes          No         Yes             Yes   
5040           No               No          No          No              No   
5041           No               No          No          No              No   
5042           No              Yes         Yes         Yes             Yes   

            Contract PaperlessBilling              PaymentMethod Churn  
0     Month-to-month              Yes           Electronic check    No  
1           One year               No               Mailed check    No  
2     Month-to-month              Yes               Mailed check   Yes  
3           One year               No  Bank transfer (automatic)    No  
4     Month-to-month              Yes           Electronic check   Yes  
...              ...              ...                        ...   ...  
5038        One year              Yes               Mailed check    No  
5039        One year              Yes    Credit card (automatic)    No  
5040  Month-to-month              Yes           Electronic check    No  
5041  Month-to-month              Yes               Mailed check   Yes  
5042        Two year              Yes  Bank transfer (automatic)    No  

[5043 rows x 19 columns]

## Feature engineering

In [32]:
corr_matrix = train.corr()    

In [34]:
corr_matrix

Column1    tenure  MonthlyCharges  TotalCharges
Column1         1.000000  0.012047       -0.010444     -0.015157
tenure          0.012047  1.000000        0.240645     -0.038729
MonthlyCharges -0.010444  0.240645        1.000000     -0.016423
TotalCharges   -0.015157 -0.038729       -0.016423      1.000000

## Feature Scaling

In [36]:
train_labels = train['Churn'].copy()

In [37]:
train = train.drop('Churn', axis=1)

In [38]:
train_num = train[["tenure", "MonthlyCharges", "TotalCharges"]] # selecting only numerical columns

In [40]:
train_labels.head()

0     No
1     No
2    Yes
3     No
4    Yes
Name: Churn, dtype: object

In [41]:
train.head()

Column1  customerID  gender SeniorCitizen Partner Dependents  tenure  \
0        0  7590-VHVEG  Female            No     Yes         No       1   
1        1  5575-GNVDE    Male            No      No         No      34   
2        2  3668-QPYBK    Male            No      No         No       2   
3        3  7795-CFOCW    Male            No      No         No      45   
4        4  9237-HQITU  Female            No      No         No       2   

  PhoneService MultipleLines InternetService  ... OnlineBackup  \
0           No            No             DSL  ...          Yes   
1          Yes            No             DSL  ...           No   
2          Yes            No             DSL  ...          Yes   
3           No            No             DSL  ...           No   
4          Yes            No     Fiber optic  ...           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  
0              Yes           Electronic check      29.850000     29.850000  
1               No               Mailed check      56.950001   1889.500000  
2              Yes               Mailed check      53.849998    108.150002  
3               No  Bank transfer (automatic)      42.299999   1840.750000  
4              Yes           Electronic check      70.699997    151.649994  

[5 rows x 21 columns]

In [44]:
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([('imputer', SimpleImputer(strategy="median")),('std_scaler', StandardScaler())])

train_num_tr = num_pipeline.fit_transform(train_num)

In [45]:
train_num_tr

array([[-1.287404  , -1.17212826, -0.03527744],
       [ 0.05803145, -0.27075245, -0.03218651],
       [-1.24663323, -0.37386193, -0.03514729],
       ...,
       [-0.87969629, -1.18044355, -0.03475122],
       [-1.16509169,  0.30965371, -0.03481745],
       [ 1.36269612,  1.34906308, -0.0239508 ]])

In [53]:
from sklearn.compose import ColumnTransformer

num_attribs = list(train_num)

cat_attribs = []

In [54]:
for i in train:
    if train[i].dtype == "object":
        cat_attribs.append(i)

In [55]:
cat_attribs

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod']

In [59]:
full_pipeline = ColumnTransformer([("num", num_pipeline, num_attribs), ("cat",OrdinalEncoder(), cat_attribs) ])

In [61]:
train_prepared = full_pipeline.fit_transform(train)

In [62]:
train_prepared

array([[-1.287404  , -1.17212826, -0.03527744, ...,  0.        ,
         1.        ,  2.        ],
       [ 0.05803145, -0.27075245, -0.03218651, ...,  1.        ,
         0.        ,  3.        ],
       [-1.24663323, -0.37386193, -0.03514729, ...,  0.        ,
         1.        ,  3.        ],
       ...,
       [-0.87969629, -1.18044355, -0.03475122, ...,  0.        ,
         1.        ,  2.        ],
       [-1.16509169,  0.30965371, -0.03481745, ...,  0.        ,
         1.        ,  3.        ],
       [ 1.36269612,  1.34906308, -0.0239508 , ...,  2.        ,
         1.        ,  0.        ]])

## Modeling

## Training and Evaluating on the Training Set

In [ ]:
cat_encoder = OrdinalEncoder()

train_cat_1hot = cat_encoder.fit_transform(train_labels.array.reshape(-1, 1)) 

train_labels = train_cat_1hot


## Linear Regression

In [70]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()

lin_reg.fit(train_prepared, train_labels)

LinearRegression()

In [73]:
train_labels = pd.DataFrame(train_labels)

In [78]:
some_data = train.iloc[:5]

some_labels = train_labels.iloc[:5]

# transform / prepare some data

some_data_prepared = full_pipeline.transform(some_data)

# make predictions

print("Predictions:", lin_reg.predict(some_data_prepared))

Predictions: [[0.45305838]
 [0.09303648]
 [0.33277979]
 [0.02544482]
 [0.56341853]]


## Measuring RMSE

### The lower rmse the best model

In [82]:
from sklearn.metrics import mean_squared_error

train_predictions = lin_reg.predict(train_prepared)
lin_mse = mean_squared_error(train_labels, train_predictions)
lin_rmse = np.sqrt(lin_mse)

lin_rmse

0.376985971059366

In [ ]:
train_labels

## cross validation

In [92]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(lin_reg, train_prepared, train_labels, scoring="neg_mean_squared_error", cv=10)

lin_rmse_scores = np.sqrt(-scores)

display_scores(lin_rmse_scores)

Scores: [0.37868623 0.37708438 0.37115534 0.37997295 0.37086477 0.3639444
 0.38377572 0.39368042 0.38137804 0.38555214]
Mean: 0.3786094413962303
Standard deviation: 0.008028006849884724


## Decision Tree

In [83]:
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor()

tree_reg.fit(train_prepared, train_labels)

DecisionTreeRegressor()

In [85]:
train_predictions = tree_reg.predict(train_prepared)

tree_mse = mean_squared_error(train_labels, train_predictions)
tree_rmse = np.sqrt(lin_mse)

tree_rmse

0.0

###  Better Evaluation Using Cross-Validation

In [86]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(tree_reg, train_prepared, train_labels, scoring="neg_mean_squared_error", cv=10)

tree_rmse_scores=np.sqrt(-scores)

In [88]:
def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard deviation:", scores.std())

In [89]:
display_scores(tree_rmse_scores)

Scores: [0.48133478 0.52652419 0.49151211 0.52326812 0.52892524 0.51946248
 0.51946248 0.51370117 0.5        0.52704628]
Mean: 0.513123684301102
Standard deviation: 0.015673322934895782


## Random Forest

In [93]:
from sklearn.ensemble import RandomForestRegressor

forest_reg = RandomForestRegressor()

forest_reg.fit(train_prepared, train_labels)

C:\Users\hp\AppData\Local\Temp\ipykernel_12072\2529907373.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  forest_reg.fit(train_prepared, train_labels)


RandomForestRegressor()

In [94]:
train_predictions = forest_reg.predict(train_prepared)

forest_mse = mean_squared_error(train_labels, train_predictions)

forest_rmse = np.sqrt(tree_mse)

In [95]:
forest_rmse

0.0

In [97]:
train_labels

0
0     0.0
1     0.0
2     1.0
3     0.0
4     1.0
...   ...
5038  0.0
5039  0.0
5040  0.0
5041  1.0
5042  0.0

[5043 rows x 1 columns]

In [96]:
forest_scores = cross_val_score(forest_reg, train_prepared, train_labels,scoring="neg_mean_squared_error", cv=10)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y wa

In [98]:
forest_rmse_scores = np.sqrt(-forest_scores)

display_scores(forest_rmse_scores)

Scores: [0.37527548 0.37918829 0.37118488 0.38397307 0.38084779 0.37572285
 0.39700716 0.3754418  0.37976758 0.3793669 ]
Mean: 0.3797775800575413
Standard deviation: 0.006674316329180491


In [6]:
train

Column1  customerID  gender SeniorCitizen Partner Dependents  tenure  \
0           0  7590-VHVEG  Female            No     Yes         No       1   
1           1  5575-GNVDE    Male            No      No         No      34   
2           2  3668-QPYBK    Male            No      No         No       2   
3           3  7795-CFOCW    Male            No      No         No      45   
4           4  9237-HQITU  Female            No      No         No       2   
...       ...         ...     ...           ...     ...        ...     ...   
5038     2038  6840-RESVB    Male            No     Yes        Yes      24   
5039     2039  2234-XADUH  Female            No     Yes        Yes      72   
5040     2040  4801-JZAZL  Female            No     Yes        Yes      11   
5041     2041  8361-LTMKD    Male           Yes     Yes         No       4   
5042     2042  3186-AJIEK    Male            No      No         No      66   

     PhoneService     MultipleLines InternetService  ... DeviceProtection  \
0              No                No             DSL  ...               No   
1             Yes                No             DSL  ...              Yes   
2             Yes                No             DSL  ...               No   
3              No                No             DSL  ...              Yes   
4             Yes                No     Fiber optic  ...               No   
...           ...               ...             ...  ...              ...   
5038          Yes               Yes             DSL  ...              Yes   
5039          Yes               Yes     Fiber optic  ...              Yes   
5040           No  No phone service             DSL  ...               No   
5041          Yes               Yes     Fiber optic  ...               No   
5042          Yes                No     Fiber optic  ...              Yes   

     TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0             No          No              No  Month-to-month              Yes   
1             No          No              No        One year               No   
2             No          No              No  Month-to-month              Yes   
3            Yes          No              No        One year               No   
4             No          No              No  Month-to-month              Yes   
...          ...         ...             ...             ...              ...   
5038         Yes         Yes             Yes        One year              Yes   
5039          No         Yes             Yes        One year              Yes   
5040          No          No              No  Month-to-month              Yes   
5041          No          No              No  Month-to-month              Yes   
5042         Yes         Yes             Yes        Two year              Yes   

                  PaymentMethod MonthlyCharges TotalCharges  Churn  
0              Electronic check      29.850000    29.850000     No  
1                  Mailed check      56.950001  1889.500000     No  
2                  Mailed check      53.849998   108.150002    Yes  
3     Bank transfer (automatic)      42.299999  1840.750000     No  
4              Electronic check      70.699997   151.649994    Yes  
...                         ...            ...          ...    ...  
5038               Mailed check      84.800000  1990.500000     No  
5039    Credit card (automatic)     103.200000  7362.900000     No  
5040           Electronic check      29.600000   346.450000     No  
5041               Mailed check      74.400000   306.600000    Yes  
5042  Bank transfer (automatic)     105.650000  6844.500000     No  

[5043 rows x 22 columns]